import '../generators/architecture.dart';
import '../generators/state_management.dart';
import '../models/project_config.dart';

/// Shared file templates that depend on the user's feature toggles
/// (localization, theming) and so are reused by every generator.

/// Builds `lib/main.dart`, wiring up theme, l10n, routing (go_router) and
/// dependency injection (get_it) based on [config].
///
/// Import paths are relative to `lib/`. When [config.useGoRouter] is set,
/// [routesImport] points at the go_router file and [routerConfigExpr] is the
/// router instance; otherwise [initialRouteExpr]/[routesMapExpr] are used.
String buildMainDart({
  required ProjectConfig config,
  required String routesImport,
  required String constantsImport,
  required String themeImport,
  required String initialRouteExpr,
  required String routesMapExpr,
  String routerConfigExpr = 'appRouter',
  String diImport = '',
  String appWidget = 'MaterialApp',
  List<String> extraPackageImports = const [],
  String runAppWrapOpen = '',
  String runAppWrapClose = '',
}) {
  final useRouter = config.useGoRouter;
  final useDi = config.enableDi;

  // With go_router we force MaterialApp.router, so a state manager's app-widget
  // import (e.g. GetX's `get` for GetMaterialApp) is no longer used. Wrapper
  // imports (e.g. Riverpod's ProviderScope) are still needed.
  final pkgImports = (useRouter && runAppWrapOpen.isEmpty)
      ? const <String>[]
      : extraPackageImports;

  final imports = <String>[
    "import 'package:flutter/material.dart';",
    ...pkgImports,
    '',
    "import '$routesImport';",
    "import '$constantsImport';",
    if (config.enableTheme) "import '$themeImport';",
    if (useDi && diImport.isNotEmpty) "import '$diImport';",
    if (config.enableL10n) "import 'l10n/app_localizations.dart';",
  ];

  final themeLines = config.enableTheme
      ? '''
      theme: AppTheme.light,
      darkTheme: AppTheme.dark,
      themeMode: ThemeMode.system,'''
      : '''
      theme: ThemeData(useMaterial3: true),''';

  final l10nLines = config.enableL10n
      ? '''
      localizationsDelegates: AppLocalizations.localizationsDelegates,
      supportedLocales: AppLocalizations.supportedLocales,'''
      : '';

  final navLines = useRouter
      ? '      routerConfig: $routerConfigExpr,'
      : '      initialRoute: $initialRouteExpr,\n'
          '      routes: $routesMapExpr,';

  final appBody = <String>[
    '      title: AppConstants.appName,',
    themeLines,
    if (l10nLines.isNotEmpty) l10nLines,
    navLines,
  ].join('\n');

  // go_router uses the .router constructor. GetMaterialApp.router doesn't accept
  // routerConfig, so when routing is delegated to go_router we use
  // MaterialApp.router universally — GetX state (controllers/Obx) still works.
  final appConstructor = useRouter ? 'MaterialApp.router' : appWidget;

  final mainFn = useDi
      ? '''
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await setupLocator();
  runApp(const ${runAppWrapOpen}MyApp()$runAppWrapClose);
}'''
      : '''
void main() {
  runApp(const ${runAppWrapOpen}MyApp()$runAppWrapClose);
}''';

  return '''
${imports.join('\n')}

$mainFn

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return $appConstructor(
$appBody
    );
  }
}
''';
}

/// A smoke test that replaces Flutter's default counter test (which breaks
/// once `main.dart` is rewritten). Keeps `flutter test` / `dart analyze` green.
///
/// [extraPackageImports] / [wrapOpen] / [wrapClose] mirror the runApp wrapper
/// so state managers that need an ancestor (e.g. Riverpod's ProviderScope)
/// still build in the test.
String buildWidgetTest(
  ProjectConfig config, {
  List<String> extraPackageImports = const [],
  String wrapOpen = '',
  String wrapClose = '',
}) {
  final imports = <String>[
    "import 'package:flutter/material.dart';",
    "import 'package:flutter_test/flutter_test.dart';",
    ...extraPackageImports,
    '',
    "import 'package:${config.projectName}/main.dart';",
  ];
  return '''
// Basic smoke test generated by nestgen.
${imports.join('\n')}

void main() {
  testWidgets('App builds without throwing', (tester) async {
    await tester.pumpWidget(const ${wrapOpen}MyApp()$wrapClose);
    await tester.pump();

    expect(find.byType(MaterialApp), findsOneWidget);
  });
}
''';
}

/// Theme file shared by both architectures when theming is enabled.
String buildAppTheme() {
  return '''
import 'package:flutter/material.dart';

/// Centralized light/dark themes. Tweak the seed color to rebrand the app.
class AppTheme {
  AppTheme._();

  static const Color _seed = Colors.indigo;

  static ThemeData get light => ThemeData(
        useMaterial3: true,
        colorScheme: ColorScheme.fromSeed(seedColor: _seed),
      );

  static ThemeData get dark => ThemeData(
        useMaterial3: true,
        brightness: Brightness.dark,
        colorScheme: ColorScheme.fromSeed(
          seedColor: _seed,
          brightness: Brightness.dark,
        ),
      );
}
''';
}

/// The l10n files (config + ARB resources) created when localization is enabled.
/// Returns a map of relative path -> contents.
Map<String, String> buildL10nFiles(ProjectConfig config) {
  return {
    'l10n.yaml': '''
arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
synthetic-package: false
''',
    'lib/l10n/app_en.arb': '''
{
  "@@locale": "en",
  "appTitle": "${config.projectName}",
  "@appTitle": {
    "description": "The application title"
  },
  "greeting": "Hello!",
  "@greeting": {
    "description": "A friendly greeting shown on the home screen"
  }
}
''',
    'lib/l10n/app_es.arb': '''
{
  "@@locale": "es",
  "appTitle": "${config.projectName}",
  "greeting": "¡Hola!"
}
''',
  };
}

/// Builds the go_router navigation file (`appRouter`). [homeImport] is the
/// import path to the home page/view relative to the router file; [homeClass]
/// is its widget class name.
String buildGoRouter({required String homeImport, required String homeClass}) {
  return '''
import 'package:go_router/go_router.dart';

import '$homeImport';

/// Application router. Add routes here and navigate with `context.go('/path')`.
final appRouter = GoRouter(
  initialLocation: '/',
  routes: [
    GoRoute(
      path: '/',
      builder: (context, state) => const $homeClass(),
    ),
  ],
);
''';
}

/// Builds the get_it service locator. Registrations are left as commented
/// examples so the file compiles for every architecture out of the box.
String buildServiceLocator() {
  return '''
import 'package:get_it/get_it.dart';

/// Global service locator. Register your dependencies in [setupLocator] and
/// resolve them anywhere with `getIt<MyType>()`.
final getIt = GetIt.instance;

Future<void> setupLocator() async {
  // Register your dependencies here. Examples:
  //
  //   getIt.registerLazySingleton<ApiService>(() => ApiService());
  //   getIt.registerFactory<HomeController>(() => HomeController(getIt()));
  //   getIt.registerSingletonAsync<Database>(() async => Database.open());
  //
  // Then resolve them with: getIt<ApiService>()
}
''';
}

/// Builds `AGENT_RULE.md` — a context file for AI coding assistants (Claude,
/// Copilot, Cursor, …) so generated code keeps the chosen architecture and
/// avoids common mistakes. Content is tailored to [config].
String buildAgentRules(ProjectConfig config) {
  final sm = config.stateManagement;
  final theme = config.enableTheme;
  final l10n = config.enableL10n;

  final buffer = StringBuffer()
    ..writeln('# AI Agent Rules — ${config.projectName}')
    ..writeln()
    ..writeln('> **Read this first.** These rules are the source of truth for any '
        'AI assistant (Claude, GitHub Copilot, Cursor, Gemini, etc.) working in '
        'this repository. Follow them so generated code stays consistent with the '
        'project architecture. _Generated by nestgen._')
    ..writeln()
    ..writeln('## Project profile')
    ..writeln()
    ..writeln('| Setting | Value |')
    ..writeln('| --- | --- |')
    ..writeln('| Package | `${config.projectName}` |')
    ..writeln('| Bundle id | `${config.packageId}` |')
    ..writeln('| Architecture | ${config.architecture.label} |')
    ..writeln('| State management | ${sm.label} |')
    ..writeln('| Theming | ${theme ? "enabled" : "disabled"} |')
    ..writeln('| Localization | ${l10n ? "enabled" : "disabled"} |')
    ..writeln()
    ..writeln(_architectureRules(config))
    ..writeln(_stateRules(config))
    ..writeln('## Conventions')
    ..writeln()
    ..writeln('- Files are `snake_case.dart`; classes are `PascalCase`; members '
        'are `camelCase`.')
    ..writeln('- One public class per file where practical; keep files small and '
        'single-responsibility.')
    ..writeln('- Match the style of the surrounding code (imports order, '
        'formatting). Run `dart format .` before committing.')
    ..writeln('- Prefer `const` constructors and immutable data where possible.')
    ..writeln();

  if (config.useGoRouter) {
    buffer
      ..writeln('## Routing (go_router)')
      ..writeln()
      ..writeln('- Navigation uses **go_router**. The router is defined as '
          '`appRouter` in the routing file.')
      ..writeln('- Add screens as `GoRoute` entries; **do not** use '
          '`Navigator.push` or a `routes:` map.')
      ..writeln('- Navigate with `context.go(\'/path\')` (replace) or '
          '`context.push(\'/path\')` (stack).')
      ..writeln('- Pass data via path/query params or the `extra` field, not '
          'global state.')
      ..writeln();
  }

  if (config.enableDi) {
    buffer
      ..writeln('## Dependency injection (get_it)')
      ..writeln()
      ..writeln('- A global service locator `getIt` is configured in '
          '`setupLocator()` (called from `main()` before `runApp`).')
      ..writeln('- Register dependencies in `setupLocator()`; resolve them with '
          '`getIt<MyType>()`. **Do not** instantiate services manually where a '
          'registration exists.')
      ..writeln('- Use `registerLazySingleton` for shared services and '
          '`registerFactory` for throwaway instances.')
      ..writeln();
  }

  if (theme) {
    buffer
      ..writeln('## Theming')
      ..writeln()
      ..writeln('- Light/dark themes live in `AppTheme`. The app uses '
          '`ThemeMode.system`.')
      ..writeln('- **Never hardcode** `Color(...)` or `TextStyle(...)` in widgets. '
          'Use `Theme.of(context).colorScheme.*` and '
          '`Theme.of(context).textTheme.*`.')
      ..writeln('- Change the brand by editing the seed color in `AppTheme`.')
      ..writeln();
  }

  if (l10n) {
    buffer
      ..writeln('## Localization (l10n)')
      ..writeln()
      ..writeln('- **All user-facing strings** must come from ARB files in '
          '`lib/l10n/` (`app_en.arb` is the template).')
      ..writeln('- Access strings with `AppLocalizations.of(context)!.<key>`.')
      ..writeln('- After adding/editing keys, run `flutter gen-l10n` (or '
          '`flutter pub get`) to regenerate `AppLocalizations`.')
      ..writeln('- Add a new key to every ARB file so translations stay in sync.')
      ..writeln();
  }

  buffer
    ..writeln('## Common mistakes to avoid')
    ..writeln()
    ..writeln('- ❌ Putting business logic, network calls, or IO directly in '
        'widgets.')
    ..writeln('- ❌ Crossing layer boundaries (see the architecture rules above).')
    ..writeln('- ❌ Adding a different state-management package — this project '
        'uses **${sm.label}**. Stay consistent.');
  if (theme) {
    buffer.writeln('- ❌ Hardcoding colors/text styles instead of using the theme.');
  }
  if (l10n) {
    buffer.writeln('- ❌ Hardcoding user-facing strings instead of using ARB/l10n.');
  }
  buffer
    ..writeln('- ❌ Leaving `flutter analyze` warnings or failing tests. Keep the '
        'project green.')
    ..writeln()
    ..writeln('## Before you finish a task')
    ..writeln()
    ..writeln('1. `flutter analyze` → must report **No issues found**.')
    ..writeln('2. `flutter test` → all tests must pass.')
    ..writeln('3. Re-read this file and confirm your changes follow every rule.');

  return buffer.toString();
}

String _architectureRules(ProjectConfig config) {
  switch (config.architecture) {
    case Architecture.clean:
      return '''
## Architecture: Clean Architecture (feature-first)

The **dependency rule**: dependencies point INWARD only.

```
presentation  ──▶  domain  ◀──  data
```

### Folder map

```
lib/
  core/        # shared: errors, usecases, network, constants, utils
  config/      # routes, theme
  features/<feature>/
    data/         # datasources, models, repositories (implementations)
    domain/       # entities, repository interfaces, usecases
    presentation/ # pages, widgets, and state holders
```

### Rules

- `domain/` is **pure Dart**: no Flutter imports, no dependency on `data/` or
  `presentation/`. It holds entities, abstract repositories, and use cases.
- `data/` **implements** the domain repository interfaces. Models extend/serialize
  entities (`fromJson`/`toJson`); data sources perform the actual IO.
- `presentation/` depends on `domain/` (via use cases) — **never** on `data/`
  directly.
- A use case does ONE thing and implements `UseCase<ResultType, Params>`.
- Shared, cross-feature code goes in `core/`. Feature code stays inside
  `features/<feature>/`.
- To add a feature, replicate the `data/ domain/ presentation/` structure under
  a new `features/<name>/` folder.
''';
    case Architecture.mvc:
      return '''
## Architecture: MVC

### Folder map

```
lib/
  models/       # plain data classes
  views/        # widgets / screens
  controllers/  # mediate between views and services (hold state)
  services/     # network / IO / persistence
  routes/       # navigation
  utils/        # helpers, constants
```

### Rules

- `models/` are plain data classes (`fromJson`/`toJson`). No UI, no business logic.
- `views/` contain widgets only. They **must not** call services/APIs directly —
  go through a controller.
- `controllers/` mediate between views and services and hold state.
- `services/` contain **all** network/IO/persistence. Keep it out of controllers
  and views.
- `routes/` is for navigation wiring only.
''';
  }
}

String _stateRules(ProjectConfig config) {
  switch (config.stateManagement) {
    case StateManagement.none:
      return '''
## State management: None (setState)

- Use `StatefulWidget` + `setState` for local UI state. Keep state minimal and
  local to the widget that owns it.
- If state needs to be shared across screens, introduce a proper state-management
  solution rather than passing callbacks deeply.
''';
    case StateManagement.provider:
      return '''
## State management: Provider

- Put `ChangeNotifier` classes in the state folder. Mutate state, then call
  `notifyListeners()`.
- Expose them with `ChangeNotifierProvider` (or `MultiProvider`) above the widgets
  that need them.
- Read once with `context.read<T>()`; rebuild on change with `context.watch<T>()`
  or a `Consumer<T>`.
- Do **not** create providers inside `build()` on every rebuild.
''';
    case StateManagement.riverpod:
      return '''
## State management: Riverpod

- Use `Notifier` + `NotifierProvider` (Riverpod 3). Keep providers in the state
  folder.
- Widgets that read providers extend `ConsumerWidget` / `ConsumerStatefulWidget`.
- Use `ref.watch(provider)` in `build()` for reactive values; use
  `ref.read(provider.notifier)` inside callbacks to call methods.
- `ProviderScope` wraps the app in `main.dart` — **keep it**.
- Do not call `ref.read` for values that should rebuild the UI — use `ref.watch`.
''';
    case StateManagement.bloc:
      return '''
## State management: Bloc (flutter_bloc)

- Model inputs as **events** (sealed classes) and outputs as **states**. Business
  logic lives in the `Bloc`/`Cubit`, never in the widget.
- Provide a bloc with `BlocProvider`; rebuild UI with `BlocBuilder`; react to
  one-off effects with `BlocListener`.
- Dispatch events via `context.read<XBloc>().add(SomeEvent())`.
- Keep blocs in the state folder; one bloc per feature concern.
''';
    case StateManagement.getx:
      return '''
## State management: GetX

- Put reactive state in a `GetxController` using `.obs` variables; mutate via
  controller methods.
- Register controllers with `Get.put(...)` and retrieve with `Get.find(...)`.
- Rebuild reactive UI with `Obx(() => ...)`.
- `main.dart` uses `GetMaterialApp` — **keep it** (GetX routing/snackbars depend
  on it). Keep heavy logic in controllers, not widgets.
''';
  }
}
