import '../models/project_config.dart';

/// Shared file templates that depend on the user's feature toggles
/// (localization, theming) and so are reused by every generator.

/// Builds `lib/main.dart`, wiring up theme + l10n based on [config].
///
/// [routesImport]/[constantsImport]/[themeImport] are import paths relative to
/// `lib/`. [homeRoute] is the initial route constant expression and
/// [routesMap] the routes map expression.
String buildMainDart({
  required ProjectConfig config,
  required String routesImport,
  required String constantsImport,
  required String themeImport,
  required String initialRouteExpr,
  required String routesMapExpr,
  String appWidget = 'MaterialApp',
  List<String> extraPackageImports = const [],
  String runAppWrapOpen = '',
  String runAppWrapClose = '',
}) {
  final imports = <String>[
    "import 'package:flutter/material.dart';",
    ...extraPackageImports,
    '',
    "import '$routesImport';",
    "import '$constantsImport';",
    if (config.enableTheme) "import '$themeImport';",
    if (config.enableL10n) "import 'l10n/app_localizations.dart';",
  ];

  final themeLines = config.enableTheme
      ? '''
      theme: AppTheme.light,
      darkTheme: AppTheme.dark,
      themeMode: ThemeMode.system,'''
      : '''
      theme: ThemeData(useMaterial3: true),''';

  final l10nLines = config.enableL10n
      ? '''
      localizationsDelegates: AppLocalizations.localizationsDelegates,
      supportedLocales: AppLocalizations.supportedLocales,'''
      : '';

  final appBody = <String>[
    '      title: AppConstants.appName,',
    themeLines,
    if (l10nLines.isNotEmpty) l10nLines,
    '      initialRoute: $initialRouteExpr,',
    '      routes: $routesMapExpr,',
  ].join('\n');

  return '''
${imports.join('\n')}

void main() {
  runApp(const ${runAppWrapOpen}MyApp()$runAppWrapClose);
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return $appWidget(
$appBody
    );
  }
}
''';
}

/// A smoke test that replaces Flutter's default counter test (which breaks
/// once `main.dart` is rewritten). Keeps `flutter test` / `dart analyze` green.
///
/// [extraPackageImports] / [wrapOpen] / [wrapClose] mirror the runApp wrapper
/// so state managers that need an ancestor (e.g. Riverpod's ProviderScope)
/// still build in the test.
String buildWidgetTest(
  ProjectConfig config, {
  List<String> extraPackageImports = const [],
  String wrapOpen = '',
  String wrapClose = '',
}) {
  final imports = <String>[
    "import 'package:flutter/material.dart';",
    "import 'package:flutter_test/flutter_test.dart';",
    ...extraPackageImports,
    '',
    "import 'package:${config.projectName}/main.dart';",
  ];
  return '''
// Basic smoke test generated by nestgen.
${imports.join('\n')}

void main() {
  testWidgets('App builds without throwing', (tester) async {
    await tester.pumpWidget(const ${wrapOpen}MyApp()$wrapClose);
    await tester.pump();

    expect(find.byType(MaterialApp), findsOneWidget);
  });
}
''';
}

/// Theme file shared by both architectures when theming is enabled.
String buildAppTheme() {
  return '''
import 'package:flutter/material.dart';

/// Centralized light/dark themes. Tweak the seed color to rebrand the app.
class AppTheme {
  AppTheme._();

  static const Color _seed = Colors.indigo;

  static ThemeData get light => ThemeData(
        useMaterial3: true,
        colorScheme: ColorScheme.fromSeed(seedColor: _seed),
      );

  static ThemeData get dark => ThemeData(
        useMaterial3: true,
        brightness: Brightness.dark,
        colorScheme: ColorScheme.fromSeed(
          seedColor: _seed,
          brightness: Brightness.dark,
        ),
      );
}
''';
}

/// The l10n files (config + ARB resources) created when localization is enabled.
/// Returns a map of relative path -> contents.
Map<String, String> buildL10nFiles(ProjectConfig config) {
  return {
    'l10n.yaml': '''
arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
synthetic-package: false
''',
    'lib/l10n/app_en.arb': '''
{
  "@@locale": "en",
  "appTitle": "${config.projectName}",
  "@appTitle": {
    "description": "The application title"
  },
  "greeting": "Hello!",
  "@greeting": {
    "description": "A friendly greeting shown on the home screen"
  }
}
''',
    'lib/l10n/app_es.arb': '''
{
  "@@locale": "es",
  "appTitle": "${config.projectName}",
  "greeting": "¡Hola!"
}
''',
  };
}
